# all:
# 	gcc -Wall -O3 kernel_driver.c -o kernel.x -mavx -mfma -mavx2 -std=c99 -Wno-nullability-completeness
# 	./kernel.x
	
# clean:
# 	rm -rf *.x *.o *~

CC = gcc
CFLAGS = -O3 -std=c99 -mavx -mfma -mavx2 -Wall -Wno-nullability-completeness

